spring:
  application:
    name: provider-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: peer1
  rabbitmq:
    addresses: 192.168.85.125
    port: 5672  # 注意，这里是5672，不是访问界面用的15672，这个是默认值
    username: admin
    password: admin
    virtual-host: /
  cloud:
    stream:
      bindings:
        # ---------消息消费-----------
        input:
          destination: messageCenterTopic
          group: emailGroup  # 拥有 group 默认会持久化队列
          contentType: application/json # 默认
        dlxOrderInput:
          destination: dlxOrderDirect
          group: orderGroup.dlq  # 拥有 group 默认会持久化队列【destination.group 构成queue名称】
          contentType: application/json # 默认
        orderDelayInput:
          destination: orderDelayTopic
          group: orderDelayGroup
          contentType: application/json # 默认
      rabbit:
        bindings:
          input:
            consumer:
              exchangeType: topic # 默认
              bindingRoutingKey: email,sms  # 将queue绑定到exchange时使用的routing key。默认'#'
              bindingRoutingKeyDelimiter: ','
              acknowledgeMode: MANUAL # 默认 AUTO
          dlxOrderInput:
            consumer:
              exchangeType: direct
              bindingRoutingKey: dlxOrderRoutingKey  # 将queue绑定到exchange时使用的routing key。默认'#'
              bindingRoutingKeyDelimiter: ','
          orderDelayInput:
            consumer:
              bindingRoutingKey: orderDelay
              delayedExchange: true # whether a delayed message exchange should be used.

# 打印项目中所有 RequestMappingHandler url
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: trace

management:
  endpoints:
    web:
      exposure:
        include: health, beans # 解禁指定 Endpoint， 默认 health,info