server:
  port: 8001

spring:
  application:
    name: customer-service

eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true #服务发现开关
    service-url:
      defaultZone: http://peer1:8761/eureka

feign:
  client:
    config:
      default:
        loggerLevel: basic #日志等级
        connectTimeout: 5000 #连接超时
        readTimeout: 5000 #读取超时