server:
  port: 8001

spring:
  application:
    name: customer-service

# 打印项目中所有 RequestMappingHandler url
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: trace

eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true #服务发现开关
    service-url:
      defaultZone: http://peer1:8761/eureka

# feign 超时设置。
# 当设置 feign.hystrix.enabled=true，启用 feign-hystrix 时会导致 feign 的超时设置失效
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: basic #日志等级
#        connectTimeout: 3000 #连接超时
#        readTimeout: 3000 #读取超时

# 开启断路器（熔断器）
feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000