spring:
  application:
    name: gateway-server
  cloud:
    # gateway相关配置
    gateway:
      # 配置允许跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # eg: "www.baidu.com"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - HEAD
            - OPTIONS
            - PATCH
      routes:
        - id: customer-service-route
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
          uri: lb://customer-service
        # 用户服务
        - id: user-service-route
          predicates:
           - Path=/user/**
          filters:
           - StripPrefix=1
          uri: http://localhost:7777
        #  用户服务（结合 服务发现实现路由）
        - id: user-service-lb-route
          predicates:
            - Path=/userUserLb/**
          filters:
            - StripPrefix=1
            - RequestTime=true
          uri: lb://user-service
      discovery:
        locator:
          enabled: true # 开启服务发现路由
          lower-case-service-id: true # 服务名转为小写
server:
  port: 9990

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka

# 通过网关服务访问分布式内部服务，自定义访问超时时间
ribbon:
  ConnectTimeout: 3000 #请求连接的超时时间
  ReadTimeout: 5000 #请求处理的超时时间

bkhech:
  jwt:
    login-url: /user/login
    #跳过认证的路由
    skip-auth-urls:
      - /baidu

# 打开 gateway Actuator API
management:
  endpoint:
    gateway:
      enabled: true # default true
  endpoints:
    web:
      exposure:
        include: gateway, health